GROQ_API_KEY = "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"   

# Instagram 設定
IG_ACCESS_TOKEN = "EAALcfHRWmrgBRJk3nKsI34lLakZBsPNTYZAZAZBB2qv6H5SkmZBScUU1fZCRvmEZBXCRCRi5tEdM9PHnaabAxobEyDIH3ZAs2FDtfJCWYNkPLa50rnS99x1gPAvI28kzDQ8FjyP5W1TYOs93NnoGmX1yZCoGO7UCPX6aGztbfNlpMlouNtlzq9siwugEVVIqxCSsBOxt8ZAM8ZD"
IG_USER_ID = "17841447892137853"

THREADS_ACCESS_TOKEN = "THAAUqg7Y3NeJBYllRbmVsT2U2MklYamhmRXRVaFVaOE52YkUxWENrdTNNd2dvNGFMSHN1WFVSRThfSlpzaHBILUVuNFFpdnJMbThkMzlkdHNaOHNxLTZAhZAGoxWEMwd1lEMnplb2R4Vms4Q2N2LWhFdy14UDRyUGtuN2ZAUTzdOcG9WZAVJuTDhNZAjZACVjBkcGcZD"
THREADS_USER_ID = "27481504961438873"